### ISSUE TITLE
Failure when partition mounted

### ISSUE THREAD

**Issue by lkraider** [rentzsch/stressdrive#5]
I ran the program against an external usb drive with the partition mounted at first and got a failure. Then, immediately afterwards I unmounted the partition and ran again then got a success. Is this to be expected?

With partition mounted:

```
$ sudo ./stressdrive /dev/rdisk1s2
disk block size: 512
disk block count: 155629664
buffer size: 8388608
succesfully created no idle assertion
writing random data to /dev/rdisk1s2
writing 100.0% (155629664 of 155629664) 00:50:18
656829fb4f79cb1bef8d385cef0ddea3823fcfd6 <= SHA-1 of written data
verifying written data
reading 100.0% (155629664 of 155629664) 00:41:28
0077823543e6e416847c36d120c7dbb03416a01c <= SHA-1 of read data
FAILURE
succesfully released no idle assertion
```

With partition unmounted:

```
$ sudo ./stressdrive /dev/rdisk1s2
Password:
disk block size: 512
disk block count: 155629664
buffer size: 8388608
succesfully created no idle assertion
writing random data to /dev/rdisk1s2
writing 100.0% (155629664 of 155629664) 00:50:16
5df635c6cbf3ed0fb9ae6db1f05cfff75adbf605 <= SHA-1 of written data
verifying written data
reading 100.0% (155629664 of 155629664) 00:41:27
5df635c6cbf3ed0fb9ae6db1f05cfff75adbf605 <= SHA-1 of read data
SUCCESS
succesfully released no idle assertion
```

**Comment by rentzsch** [comment]
For the record, stressdrive should always be run against entire unmounted physical devices. 

Practically: your device path should always be in the form of `/dev/rdiskX` (not `/dev/rdiskXsX`). stressdrive's results can only be trusted if it was allowed to fill the entire device to the device's advertised information-theoretic maximum.

If you point stressdrive at just a partition, if the drive failed during the test it's possible to get back a clean read of the random data just written, while a block outside the partition is no longer correct. That would be a false test result.

Hmm, I should probably put the above into the README.

Not withstanding all of the above, I wouldn't say this is expected behavior, but I'm not surprised. From how Disk Utility.app behaves when I execute stressdrive on an unmounted drive, I suspect the Unix subsystem treats initial writes to raw unix devices as a Disk Arbitration unmount event of some sort. It seems that may cause a flush of the HFS (or whatevs file system) initial block, overwriting stressdrive's tracked-but-random data, causing the failure.

**Comment by lkraider** [comment]
Thanks for the info. Thinking about after the fact it makes sense that a mounted partition might cause issues, but would be nice to have that on the README as a warning.
